#!/bin/sh

# cleanup
rm -rf ob_dir
rm -f sigdelay.vcd

# run verilator to translate Verilog into C++, including C++ test bench
verilator -Wall --cc --trace sigdelay.sv --exe sigdelay_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsigdelay.mk Vsigdelay

# run executable simulation file
obj_dir/Vsigdelay