#!/bin/sh

# cleanup
rm -rf ob_dir
rm -f sinegen.vcd

# run verilator to translate Verilog into C++, including C++ test bench
verilator -Wall --cc --trace sinegen.sv --exe sinegen_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsinegen.mk Vsinegen

# run executable simulation file
obj_dir/Vsinegen